### ISSUE TITLE
Company handbook template for showcase

### ISSUE THREAD

**Issue by jasonyavorsky** [kevquirk/simple.css-site#10]
I'm building https://github.com/async-go/company-handbook-template which is using simple.css to make sure everything remains as simple as possible for whoever sets it up. I'd love to have my project added to the simple.css showcase.

**Comment by kevquirk** [comment]
Happy to do this, but really need a demo page so people can see it in action. Does one exist?

**Comment by jasonyavorsky** [comment]
No not yet, apart from the links to spawn a copy in the readme. I'll look into getting something set up and get back to you.

**Comment by jasonyavorsky** [comment]
@kevquirk there's now an always-latest demo deployed to https://company-handbook-template-iota.vercel.app/. If you think I should keep adding more features before you showcase it, that's fine. It will always be a little light compared to a real site, because it's a demo of a template for building your own company handbook.

Even if you don't feature it just want to say thanks for the nice CSS template that has made my job easy!

**Comment by kevquirk** [comment]
We no longer have a showcase page.
