### ISSUE TITLE
Site addition for the showcase

### ISSUE THREAD

**Issue by phips** [kevquirk/simple.css-site#14]
Hello! I've used simple.css as the basis for what I've done with my site, [probably.co.uk](https://probably.co.uk). It's had quite a few changes and additions, but it's still clear it is the basis. My site footer acknowledges, and links to, simple.css. If you'd like to add it to the showcase you are more than welcome to. Thanks for the hard work you've put in! It's made my life much easier 😄

**Comment by kevquirk** [comment]
Hey Mark,

Your site looks broken on my iPad. Looks to be an issue with dark mode maybe?

![image](https://user-images.githubusercontent.com/16818377/149840578-b89b40fe-ad8b-4d62-8827-1f2c2a32ed40.png)

**Comment by phips** [comment]
Whoops, forgot to disable that. Will sort it and drop a note here 👍

**Comment by phips** [comment]
Fixed @kevquirk 👍

**Comment by phips** [comment]
Hello @kevquirk — do you prefer examples for the showcase to have dark mode still enabled?
