### ISSUE TITLE
Showcase Inclusion

### ISSUE THREAD

**Issue by acavella** [kevquirk/simple.css-site#15]
Hey Kev, Tony here!  Really appreciate all the hard work you've put in on simple.css.  I used a hacked up local copy of simple.css to build my original personal site, but when you announced ver. 2.0, I vowed to do it correctly.  So, throughout the day I switched my site over to the CDN hosted simple.css 2.0 and added a custom.css with my modifications.  Still a work in progress, but the ground work is laid.  

https://cavella.com

![image](https://user-images.githubusercontent.com/9434191/150014355-d38b7bf9-4b6e-4510-9d13-88f1ce7fa098.png)

**Comment by kevquirk** [comment]
Done. :-)

Great work on the site, BTW. I really like what you've done with it.
