### ISSUE TITLE
Remove ecliptik.com from showcase - no longer using simple.css

### ISSUE THREAD

**Issue by ecliptik** [kevquirk/simple.css-site#17]
@kevquirk just an fyi that I'm no longer using simple.css on my personal site ecliptik.com which is featured on https://simplecss.org/showcase.

I really enjoyed the theme and it was nice having it on the showcase, but this week I moved over to using a different theme (console.css) since I liked the terminal/gemini type look for the page.

Thank you for making simple.css, it's a wonderful framework to use.

**Comment by kevquirk** [comment]
Thanks for letting me know - that is a cool looking theme!
