### ISSUE TITLE
Showcase addition

### ISSUE THREAD

**Issue by beatquantum** [kevquirk/simple.css-site#6]
After getting fed up with the bloated Wordpress and Bootstrap css files, I decided to use simple.css for my site.
https://zerotrust.plus/

**Comment by lucienbill** [comment]
Hi, I can't access your website. Is it still online?

**Comment by kevquirk** [comment]
Site is down.

**Comment by beatquantum** [comment]
The old server was no longer useful. I have now moved simple.css to https://zerotrust.plus/ - entry edited above.
