### ISSUE TITLE
Add my weird website to the showcase

### ISSUE THREAD

**Issue by lucienbill** [kevquirk/simple.css-site#9]
Hello ! 
I made a silly website : https://getanamewithapun.pages.dev/
Would you be open to the idea of adding it to your "Showcase" page?

**Comment by oliverpool** [comment]
I agree that a "Showcase" section would be nice. For instance at the bottom of the homepage https://simplecss.org/#who-is-simplecss-for

> Who is Simple.css for?
>
> Well the short answer to that question is anyone really. But Simple.css really shines when it comes to building simple websites like a personal blog, an about page, or the basis of a new website. Some example of websites using simple.css:
> - https://getanamewithapun.pages.dev/
> - https://code.pfad.fr/vanitydoc/

(maybe being added to this list could require being a sponsor of your work ;)

**Comment by kevquirk** [comment]
We no longer have a showcase page.
